services:
  - type: web
    name: lunden-p2013
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: LAGETSE_SLUG
        value: Lundenobkpf13
    plan: free
